In [12]:
import numpy as np
from numpy import linalg as LA
import matplotlib.pyplot as plt
def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict
data=np.array(unpickle('data_batch_1') [b'data'])
label=np.array(unpickle('data_batch_1') [b'labels'])
for i in range(2,6):
    data_dict = unpickle('data_batch_'+str(i))
    data = np.concatenate((data, data_dict[b'data']))
    label = np.concatenate((label, data_dict[b'labels']))

In [13]:
cat_data=[]
for i in range(0,10):
    cat_data.append(data[label==i])

In [18]:
all_cov=np.array([np.cov(data[label==i],rowvar=False) for i in range(0,10)])
all_means=np.array([np.mean(data[label==i],axis=0) for i in range(0,10)])

In [29]:
eigv_20=[]
for i in range(0,10):
    eigv, ev= LA.eigh(all_cov[i])
    eigv_20.append(ev[:,3052:3072])

In [25]:
def Error(cat,mean1,index):
    new_data=np.matmul(np.matmul(cat-mean1,eigv_20[index]),eigv_20[index].transpose())
    new_data=new_data+mean1
    error1=np.sum(np.linalg.norm(cat-new_data,axis=1))/5000
    return error1


In [32]:
error=np.zeros((10,10))
for i in range(10):
    for j in range(i+1,10):
        A=Error(cat_data[i],all_means[i],j)
        B=Error(cat_data[j],all_means[j],i)
        error[i][j]=(A+B)/2
        error[j][i]=(A+B)/2
    print("The 3 most similar cases of", i ,"are")
    print(np.argsort(np.array(error[i,:]))[7:][::-1])


The 3 most similar cases of 0 are
[9 1 5]
The 3 most similar cases of 1 are
[7 5 9]
The 3 most similar cases of 2 are
[1 9 7]
The 3 most similar cases of 3 are
[1 9 7]
The 3 most similar cases of 4 are
[1 9 7]
The 3 most similar cases of 5 are
[1 9 7]
The 3 most similar cases of 6 are
[1 9 7]
The 3 most similar cases of 7 are
[1 9 5]
The 3 most similar cases of 8 are
[9 1 7]
The 3 most similar cases of 9 are
[1 7 5]
